[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "codefetch-cli"
version = "1.2.6"
description = "Quickly fetch code files from GitHub repositories with simple commands"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Inzamamul Qureshi", email = "inzamamulqureshi@gmail.com" }
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Topic :: Utilities",
]

[project.urls]
Homepage = "https://github.com/InzamamulQureshi/Codefetch"
Repository = "https://github.com/InzamamulQureshi/Codefetch"

[project.scripts]
codefetch = "codefetch.cli:main"
